Ecommerce/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', include('backmanage.urls', namespace='backmanage')),
    url(r'^', include('goods.urls', namespace='goods')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('orders.urls', namespace='orders')),
]

goods/urls.py
from django.conf.urls import url, include

from goods import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<spu_id>\d+)$', views.details, name='details'),
    url(r'^get_price/(?P<spu_id>\d+)$', views.get_price, name='get_price'),
    url(r'^list_page/(?P<cid>\d+)$', views.list_page, name='list_page'),
    url(r'^spu_filter/(?P<cid>\d+)$', views.spu_filter, name='spu_filter'),
    url(r'^cart_manage/$', views.cart_manage, name='cart_manage'),
    url(r'^add_cart/$', views.add_cart, name='add_cart'),
    url(r'^update_cart/$', views.update_cart, name='update_cart'),
    url(r'^del_cart_item/$', views.del_cart_item, name='del_cart_item'),
    url(r'^buy_now/$', views.buy_now, name='buy_now'),
]

orders/urls.py
from django.conf.urls import url, include

from orders import views

urlpatterns = [
    url(r'^confirm_order/$', views.confirm_order, name='confirm_order'),
    url(r'^commit_order/$', views.commit_order, name='commit_order'),
    url(r'^pay_order/$', views.pay_order, name='pay_order'),
]

users/urls.py
from django.conf.urls import url

from users import views

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^person/$', views.person, name='person'),
    url(r'^send_sms/$', views.send_sms, name='send_sms'),
    url(r'^address_manage/$', views.address_manage, name='address_manage'),
    url(r'^evaluation_manage/$', views.evaluation_manage, name='evaluation_manage'),
    url(r'^order_manage/$', views.order_manage, name='order_manage'),
    url(r'^collection_manage/$', views.collection_manage, name='collection_manage'),
    url(r'^order_info/(?P<order_id>\d+)$', views.order_info, name='order_info'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^add_address/$', views.add_address, name='add_address'),
    url(r'^set_default_address/(?P<address_id>\d+)/$', views.set_default_address, name='set_default_address'),
    url(r'^edit_address/$', views.edit_address, name='edit_address'),
    url(r'^del_address/(?P<address_id>\d+)/$', views.del_address, name='del_address'),
]

goods/views.py
from collections import Counter
from copy import deepcopy

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from backmanage.models import Advertisement
from cart.models import CartInfo
from users.models import User
from .models import TbSpu, TbSku, TbSpuPics, TbSkuAttr, TbCategory, TbBrand


# Create your views here.
def index(request):
    all_big_category = TbCategory.objects.filter(status=0, parentid=0).all()
    all_small_category = TbCategory.objects.filter(~Q(parentid=0) & Q(status=0)).all()
    all_brand = TbBrand.objects.filter(yn=0).all()
    carousel_advertisement = Advertisement.objects.filter(yn=0, type=0).order_by('order', '-create_time').all()
    static_advertisement = Advertisement.objects.filter(yn=0, type=1).order_by('order', '-create_time').all()[:4]
    banner_advertisement = Advertisement.objects.filter(yn=0, type=2).order_by('order', '-create_time').all()[:1]
    all_spu = TbSpu.objects.all()
    spu_pic_list = []
    for spu in all_spu:
        spu_pic_list.append({"spu": spu, "spu_pic": spu.spu_pic.first()})
    all_pics = TbSpuPics.objects.all()
    if request.session.get('uid'):
        amount = CartInfo.objects.filter(user=User.objects.get(pk=request.session.get('uid'))).count()
    else:
        amount = 0
    return render(request, 'goods/index.html', context={"all_big_category": all_big_category, "all_small_category": all_small_category,
                                                        "all_brand": all_brand, 'carousel_advertisement': carousel_advertisement,
                                                        'static_advertisement': static_advertisement, "banner_advertisement": banner_advertisement,
                                                        'spu_pic_list': spu_pic_list, 'amount': amount})


def details(request, spu_id):
    spu = TbSpu.objects.get(pk=spu_id)
    skus = spu.skus.all()
    sku_default = skus.first()
    attr_obj_list = []
    for sku in skus:
        for attr in sku.sku_attr.all():
            attr_obj_list.append(attr)
    attr_dict = {}
    for attr_obj in attr_obj_list:
            attr_dict[attr_obj.attr_key.name+"_"+str(attr_obj.attr_key.id)] = []

    for attr_obj in attr_obj_list:
            attr_dict[attr_obj.attr_key.name+"_"+str(attr_obj.attr_key.id)].append(attr_obj.attr_value.value+"_"+str(attr_obj.attr_value.id))

    def get_split_1(str):
        return str.split('_')[1]
    for key in attr_dict:
        value_list = list(set(attr_dict[key]))
        value_list.sort(key=get_split_1)
        attr_dict[key] = value_list

    price = sku_default.price
    if request.session.get('uid'):
        amount = CartInfo.objects.filter(user=User.objects.get(pk=request.session.get('uid'))).count()
    else:
        amount = 0
    pic_default = spu.spu_pic.order_by('id').first()
    pic_list = spu.spu_pic.order_by('id').all()
    return render(request, 'goods/details.html', context={'attr_dict': attr_dict, 'title': sku_default.title, 'price': price, 'amount': amount, 'sku_id': sku_default.id, 'spu': spu , 'pic_default': pic_default, "pic_list": pic_list})


@csrf_exempt
def get_price(request, spu_id):
    if request.method == "POST" and request.is_ajax():
        print(request.POST)
        skus = TbSpu.objects.get(unique_code=spu_id).skus.all()
        sku_id_list = [sku.id for sku in skus]
        attr_list = []
        for attr in request.POST:
            attr_list.append(TbSkuAttr.objects.filter(attr_key=attr, attr_value=request.POST.get(attr), sku_id__in=sku_id_list).values('sku_id'))
        print(attr_list)
        res = []
        for i in range(len(attr_list)):
            for j in attr_list[i]:
                res.append(j.get('sku_id'))
        print(res)
        res = dict(Counter(res))
        print(res)
        sku_id = [key for key, value in res.items()if value == len(attr_list)][0]
        price = TbSku.objects.get(pk=sku_id).price
        title = TbSku.objects.get(pk=sku_id).title
        return JsonResponse({'code': 0, 'msg': '成功', 'price': price, 'sku_id': sku_id, 'title': title})
    return redirect(reverse('goods:index'))


def list_page(request, cid):
    all_big_category = TbCategory.objects.filter(status=0, parentid=0).all()
    all_small_category = TbCategory.objects.filter(~Q(parentid=0) & Q(status=0)).all()
    category = TbCategory.objects.get(pk=cid)
    all_brand = category.brand.all()
    all_spu = category.spus.all()
    spu_pic_list = []
    for spu in all_spu:
        spu_pic_list.append({"spu": spu, "spu_pic": spu.spu_pic.first()})
    attr_dict = {}
    all_attr_key = category.attr_key.all()
    for attr_key in all_attr_key:
        attr_dict[attr_key.name] = attr_key.attr_value.all()
    if request.session.get('uid'):
        amount = CartInfo.objects.filter(user=User.objects.get(pk=request.session.get('uid'))).count()
    else:
        amount = 0
    return render(request, 'goods/all-class.html', context={'all_brand': all_brand, "all_big_category": all_big_category,
                                                            "all_small_category": all_small_category, "attr_dict": attr_dict,
                                                            "spu_pic_list": spu_pic_list, "category": category, 'amount': amount})


@csrf_exempt
def spu_filter(request, cid):
    if request.method == "POST" and request.is_ajax():
        param = deepcopy(request.POST)
        if 'brand' in param:
            spus = TbCategory.objects.get(pk=cid).spus.filter(brand=TbBrand.objects.get(pk=param['brand'])).all()
            del param['brand']
        else:
            spus = TbCategory.objects.get(pk=cid).spus.all()
        if not param:
            res_spu_list = []
            for spu in spus:
                res_spu_list.append({'unique_code': spu.unique_code, 'spu_title': spu.title, 'list_price': spu.list_pirce, 'spu_pic': spu.spu_pic.all().first().pic})
            return JsonResponse({'code': 0, 'msg': '成功', 'spu_list': res_spu_list})
        sku_id_list = []
        for spu in spus:
            for sku in spu.skus.all():
                sku_id_list.append(sku.id)
        attr_list = []
        for attr in param:
            attr_list.append(TbSkuAttr.objects.filter(attr_key=attr, attr_value=param.get(attr),
                                                      sku_id__in=sku_id_list).values('sku_id'))
        res = []
        for i in range(len(attr_list)):
            for j in attr_list[i]:
                res.append(j.get('sku_id'))
        res = dict(Counter(res))
        sku_id_list = [key for key, value in res.items() if value == len(attr_list)]
        spu_list = []
        for sku_id in sku_id_list:
            spu_list.append(TbSku.objects.get(pk=sku_id).spu)
        spu_list = list(set(spu_list))
        res_spu_list = []
        for spu in spu_list:
            res_spu_list.append({'unique_code': spu.unique_code, 'spu_title': spu.title, 'list_price': spu.list_pirce, 'spu_pic': spu.spu_pic.all().first().pic})

        return JsonResponse({'code': 0, 'msg': '成功', 'spu_list': res_spu_list})


def cart_manage(request):
    user = User.objects.get(pk=request.session.get('uid'))
    cart_list = CartInfo.objects.filter(user=user).all()
    total_price = 0
    for cart in cart_list:
        total_price += cart.total_price
    return render(request, 'goods/my-Cart.html', context={'cart_list': cart_list, 'total_price': total_price})


@csrf_exempt
def add_cart(request):
    sku = TbSku.objects.get(pk=request.POST.get('sku_id'))
    user = User.objects.get(pk=request.session.get('uid'))
    cart = CartInfo.objects.filter(product=sku, user=user).first()
    if cart:
        cart.product_count += int(request.POST.get('product_number'))
        cart.total_price = cart.product_count * cart.unit_price
    else:
        cart = CartInfo()
        cart.user = user
        cart.product = sku
        cart.product_count = int(request.POST.get('product_number'))
        cart.unit_price = TbSku.objects.get(pk=request.POST.get('sku_id')).price
        cart.total_price = cart.unit_price * cart.product_count
    cart.save()
    amount = CartInfo.objects.filter(user=user).count()
    return JsonResponse({'code': 0, 'msg': 'success', 'amount': amount})


def update_cart(request):
    cart = CartInfo.objects.get(pk=request.GET.get('id'))
    cart.product_count = request.GET.get('num')
    cart.total_price = cart.unit_price * int(request.GET.get('num'))
    cart.save()
    return JsonResponse({'code': 0, 'msg': 'success'})


def del_cart_item(request):
    cart = CartInfo.objects.get(pk=request.GET.get('id'))
    cart.delete()
    return JsonResponse({'code': 0, 'msg': 'success'})


@csrf_exempt
def buy_now(request):
    sku = TbSku.objects.get(pk=request.POST.get('sku_id'))
    if sku.cartinfo_set.exists():
        cart = sku.cartinfo_set.all()[0]
        cart.delete()
    user = User.objects.get(pk=request.session.get('uid'))
    cart = CartInfo()
    cart.user = user
    cart.product = sku
    cart.product_count = int(request.POST.get('product_number'))
    cart.unit_price = TbSku.objects.get(pk=request.POST.get('sku_id')).price
    cart.total_price = cart.unit_price * cart.product_count
    cart.save()
    request.session["cart_info_list"] = [cart.id]
    return JsonResponse({'code': 0, 'msg': 'success'})

orders/views.py
import json
import os
import time

from alipay import AliPay
from django.http import JsonResponse
from django.shortcuts import render


# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from Ecommerce.settings import BASE_DIR, MERCHANT_PRIVATE_KEY_PATH, ALIPAY_PUBLIC_KEY_PATH, APP_ID
from cart.models import CartInfo
from orders.models import OrderInfo, OrderProduct
from users.models import Address, User


@csrf_exempt
def confirm_order(request):
    cart_list = []
    total_amount = 0
    if request.method == "POST":
        cart_info_list = json.loads(request.POST.get('cart_info'))
        request.session["cart_info_list"] = cart_info_list
        return JsonResponse({'code': 0})
    if request.session.get("cart_info_list"):
        cart_info_list = request.session.get("cart_info_list")
        for cart_id in cart_info_list:
            total_amount += CartInfo.objects.get(pk=cart_id).total_price
            cart_list.append(CartInfo.objects.get(pk=cart_id))
    user = User.objects.get(pk=request.session.get('uid'))
    address_list = Address.objects.filter(user=user).order_by('is_default').all()
    return render(request, 'goods/confirm_order.html', context={'address_list': address_list, 'cart_list': cart_list, 'total_amount': total_amount})


@csrf_exempt
def commit_order(request):
    if request.method == "POST":
        address = Address.objects.get(pk=request.POST.get('address_id'))
        cart_info_list = request.session.get("cart_info_list")
        total_product_price = 0
        total_product_count = 0
        for cart_id in cart_info_list:
            total_product_price += CartInfo.objects.get(pk=cart_id).total_price
            total_product_count += CartInfo.objects.get(pk=cart_id).product_count
        orderinfo = OrderInfo()
        orderinfo.order_id = int(time.time())
        orderinfo.product_count = total_product_count
        orderinfo.product_price = total_product_price
        orderinfo.user = User.objects.get(pk=request.session.get('uid'))
        orderinfo.addr = address
        orderinfo.save()
        for cart_id in cart_info_list:
            cart = CartInfo.objects.get(pk=cart_id)
            orderproduct = OrderProduct()
            orderproduct.count = cart.product_count
            orderproduct.price = cart.unit_price * orderproduct.count
            orderproduct.product = cart.product
            orderproduct.order_info = orderinfo
            orderproduct.save()
            cart.delete()
        request.session.pop("cart_info_list")
        request.session["orderinfo_id"] = orderinfo.id
        return JsonResponse({'code': 0})
    orderinfo = OrderInfo.objects.get(pk=request.session["orderinfo_id"])
    order_product_list = orderinfo.orderproduct_set.all()
    return render(request, 'goods/d-success.html', context={"orderinfo": orderinfo, "order_product_list": order_product_list})


def pay_order(request):
    alipay = AliPay(
        appid=APP_ID,
        app_notify_url=None,
        app_private_key_path=MERCHANT_PRIVATE_KEY_PATH,
        alipay_public_key_path=ALIPAY_PUBLIC_KEY_PATH,  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥
        debug=True,  # 默认False,
    )
    if request.is_ajax() and request.META.get('HTTP_REFERER').split('/')[-2] == "order_manage":
        order = OrderInfo.objects.get(order_id=request.GET.get('order_id'))
    else:
        order = OrderInfo.objects.get(pk=request.session["orderinfo_id"])
    subject = "SX商城支付订单-%s" % order.order_id
    total_pay = order.product_price

    order_string = alipay.api_alipay_trade_page_pay(
        out_trade_no=order.order_id,
        total_amount=str(total_pay),
        subject=subject,
        return_url=None,
        notify_url=None  # 可选, 不填则使用默认notify url
    )

    pay_url = 'https://openapi.alipaydev.com/gateway.do?' + order_string
    if not request.is_ajax():
        request.session.pop("orderinfo_id")
    return JsonResponse({"res": 3, "pay_url": pay_url})


def check_pay_status(request):
    user = User.objects.get(pk=request.session.get('uid'))
    order_list = OrderInfo.objects.filter(user=user).all()
    for order in order_list:
        alipay = AliPay(
            appid=APP_ID,
            app_notify_url=None,
            app_private_key_path=MERCHANT_PRIVATE_KEY_PATH,
            alipay_public_key_path=ALIPAY_PUBLIC_KEY_PATH,  # 支付宝的公钥，验证支付宝回传消息使用，不是你自己的公钥
            debug=True,  # 默认False,
        )
        response = alipay.api_alipay_trade_query(
            out_trade_no=order.order_id
        )
        print(response)
        if response.get('trade_status') == "TRADE_SUCCESS":
            order.order_status = 2
            order.pay_date = response.get("send_pay_date")
            order.trance_num = response['trade_no']
            order.save()
    return order_list

templates/goods/my-d-info.html

{% extends 'goods/my-user.html' %}


{% block menu_bar %}
<div class="containers"><div class="pc-nav-item"><a href="#">首页</a> &gt; <a href="#">我的商城 </a> &gt; <a href="#">地址管理</a></div></div>
{% endblock menu_bar %}
{% block member-right %}
        <div class="member-right fr">
            <div class="member-head">
                <div class="member-heels fl"><h2>订单号：{{ order.order_id }}</h2></div>
                <div class="member-backs fr"><a href="{% url 'users:order_manage' %}">返回订单首页</a></div>
            </div>
            <div class="member-border">
               <div class="member-order">
                   <dl>
                       <dt>发货信息</dt>
                       <dd class="member-seller">卖家已发货 <a href="#">（物流查询）</a> </dd>
                   </dl>
                   <dl class="member-custom clearfix ">
                       <dt>订单信息</dt>
                       <dd>订单编号：{{ order.order_id }}</dd>
                       <dd>订单金额：￥{{ order.product_price }}</dd>
                       <dd>付款时间：{{ order.pay_date }}</dd>
                       <dd>创建时间：{{ order.create_time }}</dd>
                   </dl>
                   <dl>
                       <dt>配送信息</dt>
                       <dd class="member-seller"><span>收货地址：<em>{{ order.addr.a_name }}</em></span> <span>{{ order.addr.a_phone }}</span> <span>{{ order.addr.a_place }}</span></dd>
                   </dl>

                   <dl>
                       <dt>商品信息</dt>
                   </dl>
               </div>
               <div class="member-serial">
                   <ul>
                       <li class="clearfix">
                           <div class="No1">商品编号</div>
                           <div class="No2">商品详情</div>
                           <div class="No3">数量</div>
                           <div class="No4">单价</div>
                           <div class="No5">小计</div>
                       </li>
                       {% for order_product in  order_product_list %}
                            <li class="clearfix">
                               <div class="No1">{{ order_product.product.id}}</div>
                               <div class="No2"><a href="/details/{{ order_product.product.spu.unique_code}}">{{ order_product.product.title}}</a> </div>
                               <div class="No3">{{ order_product.count}}</div>
                               <div class="No4">{{ order_product.product.price}}</div>
                               <div class="No5">{{ order_product.price}}</div>
                           </li>
                       {% endfor %}
                   </ul>
               </div>
            </div>
            <div class="member-settle clearfix">
                <div class="fr">
                    <div><span>商品金额：</span><em>￥270.00</em></div>
                    <div><span>共需支付：</span><em>￥280.00</em></div>
                </div>
            </div>
        </div>
{% endblock member-right %}


templates/goods/register.html
{% load static %}
<!doctype html>
<html>
 <head>
	<meta charset="UTF-8">
	<meta name="Generator" content="EditPlus®">
	<meta name="Author" content="">
	<meta name="Keywords" content="">
	<meta name="Description" content="">
	<meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE"> 
	<meta name="renderer" content="webkit">
	<title>用户注册</title>
    <link rel="shortcut icon" type="image/x-icon" href="/static/goods/icon/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/static/goods/css/base.css">
	<link rel="stylesheet" type="text/css" href="/static/goods/css/login.css">
 </head>
 <body>

<!--- header begin-->
<header id="pc-header">
    <div class="login-header" style="padding-bottom:0">
        <div><h1><a href="{% url 'goods:index' %}"><img src="/static/goods/icon/logo.png"></a></h1></div>
    </div>
</header>
<!-- header End -->



<section id="login-content">
    <div class="login-centre">
        <div class="login-switch clearfix">
            <p class="fr">我已经注册，现在就 <a href="{% url 'users:login' %}">登录</a></p>
        </div>
        <div class="login-back">
            <div class="H-over">
                <form action="{% url 'users:register' %}" method="post">
                    {% csrf_token %}
                    <div class="login-input">
                        <label><i class="heart">*</i>用  户  名：</label>
                        <input type="text" class="list-input1" id="username" name="username" placeholder="">
                    </div>
                    <div style="color: red; margin-left: 272px"  >{{ form.username.errors }}</div>

                    <div class="login-input" >
                        <label><i class="heart">*</i>请设置密码：</label>
                        <input type="password" class="list-input" id="password" name="password" placeholder="">
                    </div>
                     <div style="color: red; margin-left: 272px">{{ form.password.errors }}</div>

                    <div class="login-input">
                        <label><i class="heart">*</i>请确认密码：</label>
                        <input type="password" class="list-input" id="confirm_password" name="confirm_password" placeholder="">
                    </div>
                    <div style="color: red; margin-left: 272px">{{ form.confirm_password.errors }}</div>

                    <div class="login-input">
                        <label><i class="heart">*</i>电子邮箱：</label>
                        <input type="text" class="list-input" id="email" name="email" placeholder="">
                    </div>
                    <div style="color: red; margin-left: 272px">{{ form.email.errors }}</div>

                    <div class="login-input">
                        <label><i class="heart">*</i>手  机  号：</label>
                        <input type="text" class="list-iphone" id="iphone" name="phone" placeholder="">
                        <a href="javascript:void(0)" class="obtain" onclick="send_sms()">获取短信验证码</a>
                    </div>
                    <div style="color: red; margin-left: 272px">{{ form.phone.errors }}</div>

                    <div class="login-input">
                        <label><i class="heart">*</i>短信验证码：</label>
                        <input type="text" class="list-notes" id="message" name="sms" placeholder="">
                    </div>

                    <div class="item-ifo">
                        <input type="checkbox" onClick="agreeonProtocol();" id="readme" checked="checked" class="checkbox">
                        <label for="protocol">我已阅读并同意<a id="protocol" class="blue" href="http://in.m.jd.com/help/app/register_info.html">《用户协议》</a></label>
                        <span class="clr"></span>
                    </div>

                  <div class="login-button" >
                      <input type="submit" value="立即注册" style='height: 20%; width: 200px; font-size:80px'>
                  </div>
{#                    <div class="login-button">#}
{#                        <a href="{% url 'users:register' %}">立即注册</a>#}
{#                    </div>#}
                </form>
            </div>
        </div>
    </div>
</section>

<!--- footer begin-->
<footer id="footer">
    <div class="containers">
        <div class="w" style="padding-top:30px">
            <div id="footer-2013">
                <div class="links">
                    <a href="">关于我们</a>
                    |
                    <a href="">联系我们</a>
                    |
                    <a href="">人才招聘</a>
                    |
                    <a href="">商家入驻</a>
                    |
                    <a href="">广告服务</a>
                    |
                    <a href="">手机京东</a>
                    |
                    <a href="">友情链接</a>
                    |
                    <a href="">销售联盟</a>
                    |
                    <a href="">English site</a>
                </div>
                <div style="padding-left:10px">
                    <p style="padding-top:10px; padding-bottom:10px; color:#999">网络文化经营许可证：浙网文[2013]0268-027号| 增值电信业务经营许可证：浙B2-20080224-1</p>
                    <p style="padding-bottom:10px; color:#999">信息网络传播视听节目许可证：1109364号 | 互联网违法和不良信息举报电话:0571-81683755</p>
                </div>
            </div>
        </div>

    </div>
</footer>
<!-- footer End -->
</body>
</html>
<script type="text/javascript" src="/static/goods/js/jquery.js"></script>
<script>
    function send_sms() {
        $.get("{% url 'users:send_sms' %}", {'phone':$("#iphone").val()})
    }
</script>