Ecommerce/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', include('backmanage.urls', namespace='backmanage')),
    url(r'^', include('goods.urls', namespace='goods')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('orders.urls', namespace='orders')),
]

backmanage/urls.py
from django.conf.urls import url

from backmanage import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^account/$', views.account_detail, name='account'),
    url(r'^add_brand/$', views.add_brand, name='add_brand'),
    url(r'^admin_competence/$', views.admin_competence, name='admin_competence'),
    url(r'^admin_info/$', views.admin_info, name='admin_info'),
    url(r'^administrator/$', views.administrator, name='administrator'),
    url(r'^ads_list/$', views.ads_list, name='ads_list'),
    url(r'^advertising/$', views.advertising, name='advertising'),
    url(r'^amount/$', views.amount, name='amount'),
    url(r'^article_add/$', views.article_add, name='article_add'),
    url(r'^article_list/$', views.article_list, name='article_list'),
    url(r'^article_sort/$', views.article_sort, name='article_sort'),
    url(r'^brand_details/$', views.brand_details, name='brand_details'),
    url(r'^brand_manage/$', views.brand_manage, name='brand_manage'),
    url(r'^category_manage/$', views.category_manage, name='category_manage'),
    url(r'^competence/$', views.competence, name='competence'),
    url(r'^competence/(\d+)/$', views.competence, name='competence'),
    url(r'^cover_management/$', views.cover_management, name='cover_management'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^guestbook/$', views.guestbook, name='guestbook'),
    url(r'^home/$', views.home, name='home'),
    url(r'^integration/$', views.integration, name='integration'),
    url(r'^member_grading/$', views.member_grading, name='member_grading'),
    url(r'^member_show/(?P<type>\d+)/$', views.member_show, name='member_show'),
    url(r'^order_chart/$', views.order_chart, name='order_chart'),
    url(r'^order_detailed/$', views.order_detailed, name='order_detailed'),
    url(r'^order_handling/$', views.order_handling, name='order_handling'),
    url(r'^orderform/$', views.orderform, name='orderform'),
    url(r'^payment_configure/$', views.payment_configure, name='payment_configure'),
    url(r'^payment_details/$', views.payment_detail, name='payment_detail'),
    url(r'^payment_method/$', views.payment_method, name='payment_method'),
    url(r'^product_add/$', views.product_add, name='product_add'),
    url(r'^category_add/$', views.category_add, name='category_add'),
    url(r'^category_update/(?P<cid>\d+)/$', views.category_update, name='category_update'),
    url(r'^category_update/$', views.category_update, name='category_update'),
    url(r'^category_list/$', views.category_list, name='category_list'),
    url(r'^product_list/$', views.pruduct_list, name='product_list'),
    url(r'^refund/$', views.refund, name='refund'),
    url(r'^refund_detailed/$', views.refund_detailed, name='refund_detailed'),
    url(r'^shop_list/$', views.shop_list, name='shop_list'),
    url(r'^shopping_detailed/$', views.shopping_detailed, name='shopping_detailed'),
    url(r'^shops_audit/$', views.shops_audit, name='shops_audit'),
    url(r'^sort_ads/$', views.sort_ads, name='sort_ads'),
    url(r'^system_logs/$', views.system_logs, name='system_logs'),
    url(r'^system_section/$', views.system_section, name='system_section'),
    url(r'^systems/$', views.systems, name='systems'),
    url(r'^transaction/$', views.transaction, name='transaction'),
    url(r'^user_list/$', views.user_list, name='user_list'),
    url(r'^add_competence/$', views.add_competence, name='add_competence'),
    url(r'^add_admin/$', views.add_admin, name='add_admin'),
    url(r'^attribute_list/(?P<cid>\d+)/$', views.attribute_list, name='attribute_list'),
    # url(r'^attribute_list/$', views.attribute_list, name='attribute_list'),
    url(r'^attribute_update/$', views.attribute_update, name='attribute_update'),
    url(r'^attribute_delete/$', views.attribute_delete, name='attribute_delete'),
    url(r'^attribute_add/$', views.attribute_add, name='attribute_add'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^verficode/$', views.verficode, name='verficode'),
    url(r'^attribute_get/$', views.attribute_get, name='attribute_get'),
    url(r'^sku_add/(?P<bcid>\d+)/(?P<scid>\d+)/(?P<unique_code>\d+)/$', views.sku_add, name='sku_add'),
    url(r'^sku_add/$', views.sku_add, name='sku_add'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^delete_all/$', views.delete_all, name='delete_all'),
    url(r'^update_advertising/$', views.update_advertising, name='update_advertising'),
    url(r'^del_advertising/$', views.del_advertising, name='del_advertising'),



]

goods/urls.py
from django.conf.urls import url, include

from goods import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^details/(?P<spu_id>\d+)$', views.details, name='details'),
    url(r'^get_price/(?P<spu_id>\d+)$', views.get_price, name='get_price'),
    url(r'^list_page/(?P<cid>\d+)$', views.list_page, name='list_page'),
    url(r'^spu_filter/(?P<cid>\d+)$', views.spu_filter, name='spu_filter'),
    url(r'^cart_manage/$', views.cart_manage, name='cart_manage'),
    url(r'^add_cart/$', views.add_cart, name='add_cart'),
    url(r'^update_cart/$', views.update_cart, name='update_cart'),
    url(r'^del_cart_item/$', views.del_cart_item, name='del_cart_item'),
    url(r'^buy_now/$', views.buy_now, name='buy_now'),
]

orders/urls.py
from django.conf.urls import url, include

from orders import views

urlpatterns = [
    url(r'^confirm_order/$', views.confirm_order, name='confirm_order'),
    url(r'^commit_order/$', views.commit_order, name='commit_order'),
    url(r'^pay_order/$', views.pay_order, name='pay_order'),
]

backmanage/views.py
import hashlib
import json
import os
from datetime import datetime
from itertools import count
from random import randint

from django.contrib.messages.storage import session
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from Ecommerce import settings
from Ecommerce.settings import SECRET_KEY
from backmanage.models import *

import json

# Create your views here.
from backmanage.verfiCode import VerfiCode
from goods.models import TbCategory, TbAttributeKey, TbSpuPics
from goods.models import TbCategory, TbAttributeKey, TbAttributeValue
from goods.models import TbCategory, TbAttributeKey, TbAttributeValue, TbSku, TbBrand, TbSpu, TbSkuAttr
from users.models import User


def add_competence(request):
    comp = {'超级管理员': '拥有至高无上的权利,操作系统的所有权限', '普通管理员': '拥有网站系统大部分使用权限,无权限管理功能', '编辑管理员': '拥有部分权限,主要进行编辑功能,无编辑订单功能,权限分配功能'}
    for key, value in comp.items():
        res = Privilege()
        res.privilege_name = key
        res.describe = value
        res.menu_list = [0]
        res.save()
    return HttpResponse('添加权限')


def add_admin(request):
    admin = Admin()
    admin.admin_name = 'lixiaoni'
    admin.admin_password = hashlib.sha1(b'a123').hexdigest()
    admin.admin_age = '22'
    admin.admin_sex = False
    admin.admin_reg_date = datetime.now()
    admin.admin_login_ip = request.META['REMOTE_ADDR']
    admin.admin_login_addr = '北京海淀'
    admin.admin_email = '1134492261@qq.com'
    admin.admin_phone = 17635144631
    admin.admin_qq = '1134492261'
    admin.privilege = Privilege.objects.get(id=13)
    admin.save()
    return HttpResponse('add_admin')


def index(request):
    if request.session.get("admin_id"):
        username = request.session.get('admin_username')
        data = Privilege.objects.filter(admin=request.session.get("admin_id")).all()[0]
        return render(request, 'backmanage/index.html', context={'username': username, 'data': data})
    return redirect(reverse("backmanage:login"))


def login(request):
    if request.is_ajax():
        username = request.POST.get('username')
        password = request.POST.get('password')
        password_hash = hashlib.sha1(password.encode('utf8')).hexdigest()
        code = request.POST.get('code')
        verficode = request.session['admin_verficode']
        res = Admin.objects.filter(admin_name=username, admin_password=password_hash).values('id', 'admin_name')
        if len(res) > 0 and verficode == code:  # 登录成功
            request.session['admin_id'] = res[0]['id']
            request.session['admin_username'] = res[0]['admin_name']
            return JsonResponse({'code': 1, 'msg': 'ok'}, safe=False)
        return JsonResponse({'code': 0, 'msg': 'failed'}, safe=False)
    return render(request, 'backmanage/login.html')


def account_detail(request):
    return render(request, 'backmanage/Account_Details.html')


def add_brand(request):
    all_big_category = TbCategory.objects.filter(status=0, parentid=0).all()
    all_small_category = TbCategory.objects.filter(status=0).exclude(parentid=0).all()
    if request.method == "POST":
        brand = TbBrand()
        brand.name = request.POST['bname']
        file = request.FILES.get('brlogo')
        try:
            path = os.path.join(settings.STATIC_ROOT, 'upload/'+file.name)
        except Exception as e:
            path = os.path.join(settings.MEDIA_ROOT, file.name)
        ext = os.path.splitext(file.name)
        if len(ext) < 1 or not ext[1] in settings.ALLOWED_FILEEXTS:
            return redirect(reverse('backmanage:add_brand'))
        brand.logo = 'upload/' + file.name
        if os.path.exists(path):
            dir1 = datetime.today().strftime("%Y/%m/%d")
            try:
                dir = os.path.join(settings.STATIC_ROOT, 'upload/' + dir1)
            except Exception as e:
                dir = os.path.join(settings.MEDIA_ROOT, dir1)
            if not os.path.exists(dir):
                os.makedirs(dir)
            file_name = ext[0] + datetime.today().strftime("%Y%m%d%H%M%S") + str(randint(1, 1000)) + ext[1] if len(ext) > 1 else ''
            path = os.path.join(dir, file_name)
            dir2 = os.path.join(dir1, file_name)
            brand.logo = 'upload/' + dir2
        with open(path, 'wb') as fp:
            if file.multiple_chunks():
                for block1 in file.chunks():
                    fp.write(block1)
            else:
                fp.write(file.read())
        brand.yn = request.POST['checkbox']
        brand.category = TbCategory.objects.filter(id=request.POST['s_cid'])[0]
        brand.save()
        return redirect(reverse('backmanage:brand_manage'))

    return render(request, 'backmanage/Add_Brand.html', context={'all_big_category': all_big_category, 'all_small_category':  all_small_category})


def admin_competence(request):
    number = Privilege.objects.count()
    privilege = []
    privileges = Privilege.objects.all()
    for p in privileges:

        privilege.append({'privilege': p, 'users': p.admin.values('admin_name'), 'usercount':p.admin.count()})

    return render(request, 'backmanage/admin_Competence.html', context={'number': number, 'privilege': privilege})


def admin_info(request):
    if request.method == 'POST':
        oldpwd = request.POST.get('oldpwd')
        oldpassword_hash = hashlib.sha1(oldpwd.encode('utf8')).hexdigest()

        newpwd = request.POST.get('newpwd')
        newpassword_hash = hashlib.sha1(newpwd.encode('utf8')).hexdigest()

        confirm_newpwd = request.POST.get('confirm_newpwd')
        confirm_pwd = hashlib.sha1(confirm_newpwd.encode('utf8')).hexdigest()

        res = Admin.objects.filter(admin_name=request.session.get('admin_username')).update(admin_password=newpassword_hash)
        print(oldpwd, oldpassword_hash, newpwd, newpassword_hash, confirm_newpwd, confirm_pwd, res)
        return JsonResponse({'code': 1, 'msg': 'ok'}, safe=False)

    admin_name = request.session.get('admin_username')
    info = Admin.objects.get(admin_name=request.session.get('admin_username'))
    return render(request, 'backmanage/admin_info.html', context={'admin_name': admin_name, 'info': info})


def administrator(request):
    if request.method == 'POST':
        user_name = request.POST.get('username')
        userpassword = request.POST.get('password')
        userpassword_hash = hashlib.sha1(userpassword.encode('utf8')).hexdigest()
        user_sex = request.POST.get('form-field-radio')
        login_ip = request.META['REMOTE_ADDR']
        user_tel = request.POST.get('user-tel')
        email = request.POST.get('email')
        user_qq = request.POST.get('user-qq')
        privilege = Privilege.objects.filter(id=request.POST.get('admin-role'))[0]
        reg_date = datetime.now()
        admin = Admin(admin_name=user_name, admin_password=userpassword_hash, admin_sex=user_sex, admin_phone=user_tel,
                      admin_email=email, admin_reg_date=reg_date, admin_login_ip=login_ip, admin_qq=user_qq,
                      privilege=privilege)
        admin.save()
        return JsonResponse({'code': 1, 'msg': 'ok'}, safe=False)
    admin_total = Admin.objects.count()
    admins = Admin.objects.all()
    privileges = Privilege.objects.all()
    return render(request, 'backmanage/administrator.html',
                  context={'admin_total': admin_total, 'admins': admins, 'privileges': privileges})


def ads_list(request):
    return render(request, 'backmanage/Ads_list.html')


@csrf_exempt
def advertising(request):
    if request.method == "POST":
        path = os.path.join(settings.MEDIA_ROOT, 'ad')
        print(request.POST)
        file = request.FILES.get('picture')
        path = os.path.join(path, file.name)
        # 创建新文件
        with open(path, 'wb') as fp:
            # 如果文件超过2.5M,则分块读写
            if file.multiple_chunks():
                for block1 in file.chunks():
                    fp.write(block1)
            else:
                fp.write(file.read())
        ad = Advertisement()
        ad.type = request.POST.get('class')
        ad.order = request.POST.get('order')
        ad.yn = request.POST.get('yn')
        ad.pic = 'upload/ad/' + file.name
        ad.save()
        return JsonResponse({'code': 0, 'msg': 'success'})
    ads = Advertisement.objects.order_by('id').all()
    return render(request, 'backmanage/advertising.html', context={'ad_list': ads})


def amount(request):
    return render(request, 'backmanage/Amounts.html')


def article_add(request):
    return render(request, 'backmanage/article_add.html')


def article_list(request):
    return render(request, 'backmanage/article_list.html')


def article_sort(request):
    return render(request, 'backmanage/article_Sort.html')


def brand_details(request,id=0):
    brands = TbBrand.objects.get(pk=id)
    return render(request, 'backmanage/Brand_detailed.html',context={'brands':brands})


def brand_manage(request):
    brands = TbBrand.objects.all()
    return render(request, 'backmanage/Brand_Manage.html',context={'brands':brands})


def category_manage(request):
    category = TbCategory.objects.values('id', 'name', 'parentid').filter(status=0).order_by('order').all()
    return render(request, 'backmanage/Category_Manage.html', context={'categorys': category})


def category_list(request):
    category = TbCategory.objects.filter(status=0).order_by('order').all()
    count = TbCategory.objects.filter(status=0).count()
    all_big_category = TbCategory.objects.filter(status=0, parentid=0).all()
    # todo 按照大类目分组显示小类目
    return render(request, 'backmanage/Category_list.html',
                  context={'categorys': category, 'count': count, 'all_big_category': all_big_category})


@csrf_exempt
def category_add(request):

templates/backmanage/Category_list.html
<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>商品列表</title>
<link rel="stylesheet" type="text/css" href="/static/backmanage/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/static/backmanage/css/style.css">
<link rel="stylesheet" type="text/css" href="/static/backmanage/css/font-awesome.min.css">
<script src="/static/backmanage/js/jquery-1.9.1.min.js"></script>
</head>
<body class="user-select">
    <section class="container-fluid">
        <div class="row">
            <div class="" id="main">
                <div class="row">
                    <div class="">
                        <h1 class="page-header">管理
                            <span class="badge">{{ count }}</span>
                        </h1>
                        <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>名称</th>
                                    <th>显示顺序</th>
                                    <th>描述</th>
                                    <th>操作</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for big_category in all_big_category %}
                                    <tr class="danger">
                                        <td>{{ big_category.name }}</td>
                                        <td>{{ big_category.order }}</td>
                                        <td>{% if big_category.description %}
                                                {{ big_category.description }}
                                            {% else %}
                                                无
                                            {% endif %}
                                        </td>
                                        <td>
                                            <a href="{% url 'backmanage:category_update' big_category.id %}">
                                                修改
                                            </a>
                    {#                      <a rel="1">删除</a></td>#}
                    {#                  todo 删除级联影响略大，暂时未做#}
                                    </tr>
                                    {% for category in categorys %}
                                        {% if category.parentid == big_category.id %}
                                            <tr>
                                                <td>{{ category.name }}</td>
                                                <td>{{ category.order }}</td>
                                                <td>
                                                    {% if category.description %}
                                                        {{ category.description }}
                                                    {% else %}无
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    <a href="{% url 'backmanage:category_update' category.id %}">
                                                        修改
                                                    </a>
                        {#                          <a rel="1">删除</a></td>#}
                        {#                          todo 删除级联影响略大，暂时未做#}
                                                </td>
                                            </tr>
                                       {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </tbody>
                        </table>
{#                      <span class="prompt-text"><strong>注：</strong>删除一个类目也会删除该下的子目和商品,请谨慎删除!</span> </div>#}
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="Operate_btn">
                <a href="{% url 'backmanage:category_add' %}" class="btn  btn-warning">
                    <i class="icon-edit align-top bigger-125"></i>新增子类型
                </a>
            </div>
        </div>
    </section>
    <script src="/static/backmanage/js/bootstrap.min.js"></script>
    <script src="/static/backmanage/js/admin-scripts.js"></script>
    <script>
    //是否确认删除
    $(function(){
        $("#main table tbody tr td a").click(function(){
            var name = $(this);
            var id = name.attr("rel"); //对应id
            if (event.srcElement.outerText === "删除")
            {
                if(window.confirm("此操作不可逆，是否确认？"))
                {
                    $.ajax({
                        type: "POST",
                        url: "/Category/delete",
                        data: "id=" + id,
                        cache: false, //不缓存此页面
                        success: function (data) {
                            window.location.reload();
                        }
                    });
                };
            };
        });
    });
    </script>
</body>
</html>

templates/backmanage/integration.html
{% load static %}
{% load customfilter %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Cache-Control" content="no-siteapp"/>
    <link href="{% static 'backmanage/assets/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static 'backmanage/css/style.css' %}"/>
    <link href="{% static 'backmanage/assets/css/codemirror.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'backmanage/assets/css/ace.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'backmanage/assets/css/font-awesome.min.css' %}"/>
    <!--[if lte IE 8]>
		  <link rel="stylesheet" href="{% static 'backmanage/assets/css/ace-ie.min.css' %}" />
		<![endif]-->
    <script src="{% static 'backmanage/js/jquery-1.9.1.min.js' %}"></script>
    <script src="{% static 'backmanage/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'backmanage/assets/js/typeahead-bs2.min.js' %}"></script>
    <script src="{% static 'backmanage/assets/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'backmanage/assets/js/jquery.dataTables.bootstrap.js' %}"></script>
    <script src="{% static 'backmanage/assets/layer/layer.js' %}" type="text/javascript"></script>
    <script src="{% static 'backmanage/assets/laydate/laydate.js' %}" type="text/javascript"></script>
    <title>会员记录管理</title>
</head>

<body>
<div class="margin clearfix">
    <div class="" id="Other_Management">
        <div class="border clearfix">
       <span class="l_f">
        <a href="" onclick="member_delAll()" class="btn btn-danger"><i class="fa fa-trash"></i>&nbsp;批量删除</a>
       </span>
            <span class="r_f">共：<b>{{ user_total }}</b>条</span>
        </div>
        <div class="list_style">
            <table class="table table-striped table-bordered table-hover" id="sample-table">
                <thead>
                <tr>
                    <th width="25"><label><input type="checkbox" class="ace"><span class="lbl"></span></label></th>
                    <th width="80">用户ID</th>
                    <th width="100">用户名</th>
                    <th width="80">积分</th>
                    <th width="120">浏览记录(条)</th>
                    <th width="120">购物记录(单)</th>
                    <th width="250">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for all in user %}
                <tr>
                    <td><label><input type="checkbox" class="myclass" id="checkId_ƒ{{ all.id }}"
                                              value="{{ all.id }}"><span class="lbl"></span></label></td>
                    <td>{{ all.id }}</td>
                    <td>{{ all.username }}</td>
                    <td><a href="javascript:void(0)" onclick="integration_history('23')">{{ all.grade }}</a></td>
                    <td><a href="javascript:void(0)" onclick="Browse_history('13')">3434</a></td>
                    <td><a href="javascript:void(0)" onclick="Order_history('{{all.id }}')">{{ order_total }}</a></td>
                    <td><a title="删除" href="" onclick="member_del(this,'{{ all.id }}')" class="btn btn-xs btn-warning"><i
                            class="fa fa-trash  bigger-120"></i>删除</a>
                    </td>
                </tr>
                {% endfor %}

                </tbody>
            </table>
        </div>

    </div>
</div>
<!--积分-->
<div id="integration_history" style="display:none; padding:10px;">
    <table class="table table-striped table-bordered table-hover" id="integration_history_list" width="100%">
        <thead>
        <tr>
            <th width="80">用户</th>
            <th width="100">产品名称</th>
            <th width="80">价格(元)</th>
            <th width="120">积分</th>
            <th width="120">获得时间</th>
        </tr>
        </thead>
        <tbody>
        {% for buy in order %}
        <tr>
            <td>{{ buy.user.username }}</td>
            <td>华为 HUAWEI P30 8GB+512GB天空之境全网通双4G手机</td>
            <td>{{ buy.product_price }}</td>
            <td>{{ buy.user.grade }}</td>
            <td>{{ buy.pay_date }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>

</div>
<!--浏览记录-->
<div id="Browse_history" style="display:none; padding:10px">
    <table class="table table-striped table-bordered table-hover" id="Browse_history_list" width="100%">
        <thead>
        <tr>
            <th width="80">用户</th>
            <th width="100">产品名称</th>
            <th width="80">价格(元)</th>
            <th width="120">浏览次数</th>
            <th width="120">最新时间</th>
        </tr>
        </thead>
        <tbody>
        {% for buy in order %}
        <tr>
            <td>{{ buy.user.username }}</td>
            <td><a href="#">荣耀7i 海岛蓝 移动4G手机 双卡双待 </a></td>
            <td>{{ buy.product_price }}</td>
            <td>1234</td>
            <td>{{ buy.create_time }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>


</div>

<!--购物记录-->
<div id="Order_history" style="display:none; padding:10px;">

    <table class="table table-striped table-bordered table-hover" id="Order_history_list" width="100%">
        <thead>

        <tr>
            <th width="80">用户名</th>
            <th width="100">订单号</th>
            <th width="80">数量</th>
            <th width="120">交易状态</th>
            <th width="120">交易时间</th>
        </tr>
        </thead>
        <tbody>
        {% for buy in order %}
        <tr>
            <td>{{ buy.user.username }}</td>
            <td>{{ buy.order_id }}</td>
            <td>{{ buy.product_count }}</td>
            <td>{{ buy.ORDER_status|getvalue:buy.order_status }}</td>
            <td>{{ buy.pay_date }}</td>
        </tr>
        {% endfor %}

        </tbody>
    </table>
</div>
</body>
</html>
<script>
    jQuery(function ($) {
        var oTable1 = $('#sample-table').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [
                //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
                {"orderable": false, "aTargets": [0, 2, 3, 6]}// 制定列不参与排序
            ]
        });


        $('table th input:checkbox').on('click', function () {
            var that = this;
            $(this).closest('table').find('tr > td:first-child input:checkbox')
                .each(function () {
                    this.checked = that.checked;
                    $(this).closest('tr').toggleClass('selected');
                });

        });
    });


    /*用户-删除*/

    function member_delAll() {
        let ids = new Array();
        $(".myclass").each(function (i) {
            if ($(this).is(":checked")) {
                var tmp = $(this).val();
                ids.push(tmp);
            }
        })
        $.ajax({
            url: "{% url 'backmanage:delete_all' %}",
            method: "POST",
            dataType: "JSON",
            data: {ids: ids.toString()},
            async: false,
            success: function (data, status) {
                if (status == 200) {

                    layer.msg('已删除!', {icon: 1, time: 1000})
                }
                //
            }
        });

    }

    function member_del(obj1, id) {
        $.ajax({
            url: "{% url 'backmanage:delete' %}",
            method: "POST",
            dataType: "JSON",
            data: {id: id},
            async: false,
            success: function (data, status) {
                if (status == 200) {
                    layer.msg('已删除!', {icon: 1, time: 1000})
                }
                //
            }

        });
    }

    //积分浏览
    function integration_history(id) {
        layer.open({
            type: 1,
            title: '积分获取记录',
            area: ['800px', '400px'],
            shadeClose: true,
            content: $('#integration_history'),
        })
        $('#integration_history_list').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [{
                "bSortable": false,
                "orderable": false,
                "aTargets": [0, 1]
            }]
        });

    };

    //浏览记录

    function Browse_history(id) {
        layer.open({
            type: 1,
            title: '浏览记录',
            area: ['800px', '400px'],
            shadeClose: true,
            content: $('#Browse_history'),
        })
        $('#Browse_history_list').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [{
                "bSortable": false,
                "orderable": false,
                "aTargets": [0, 1]
            }]
        });
    }


    //购物记录

    function Order_history(id) {
        $.get({% url 'backmanage:integration' %}, {id:'id'}, function (data) {
            layer.open({
            type: 1,
            title: '购物记录',
            area: ['800px', '400px'],
            shadeClose: true,
            content: $('#Order_history' + data),
        });
        $('#Order_history_list').dataTable({
            "aaSorting": [[1, "desc"]],//默认第几个排序
            "bStateSave": true,//状态保存
            "aoColumnDefs": [{
                "bSortable": false,
                "orderable": false,
                "aTargets": [0, 1]
            }]
        });
            $(".Order_history input")
        })

    }


</script>